[project]
name = "cv-creator-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.124.4",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
